### ISSUE TITLE
Audio previously working but not working after rebuild

### ISSUE THREAD

**Issue by RodBarnes** [WeirdTreeThing/chromebook-linux-audio#301]
**Describe the bug**
I was previously successful getting audio to work on my Sand/APL chromebook with no issues regarding excess volume or anything -- see this this [thread](https://github.com/WeirdTreeThing/chromebook-linux-audio/issues/63#issuecomment-2311357065).   It is an Acer CB515, using Mr. Chromebox firmware and running LinuxMint 22 w kernel 6.11

But I recently rebuilt my laptop and now the script no longer fixes the audio.  I used the `--force-avs-install` option this time where, before, we were instructed to use `sof` or something like that?

An important difference I note is that, under the previous system `inxi -A` showed:

```
Audio:
  Device-1: Intel Celeron N3350/Pentium N4200/Atom E3900 Series Audio Cluster
    driver: sof-audio-pci-intel-apl bus-ID: 00:0e.0 chip-ID: 8086:5a98
  Sound Server-1: ALSA v: k6.6.0-chrultrabook running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
```

But under this rebuild it shows:
```
Audio:
  Device-1: Intel Celeron N3350/Pentium N4200/Atom E3900 Series Audio Cluster driver: snd_soc_avs
    v: kernel bus-ID: 00:0e.0 chip-ID: 8086:5a98 class-ID: 0401
  API: ALSA v: k6.11.0-26-generic status: kernel-api
  Server-1: PipeWire v: 1.0.5 status: active with: 1: pipewire-pulse status: active
    2: wireplumber status: active 3: pipewire-alsa type: plugin
```

So, the SOF driver isn't showing up anymore which, I assume, is because it has been deprecated in favor of AVS?

**Boardname**
Sand

**Logs**
debuggin.sh log output is attached
[debug-logs-Sand-2025-06-11_12h46m.tar.gz](https://github.com/user-attachments/files/20696457/debug-logs-Sand-2025-06-11_12h46m.tar.gz)
